### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by guillenjsa** [kattatzu/sbif#7]
Good afternoon

Dear,

Currently I have a problem with the api when downloading any exchange rate to the UF currency and this does not always happen, there are days that we can obtain the rates of the day correctly, but others not, as is the case today. The API returns the following message: Division by zero

We are looking forward to your comments. Regards!

**Comment by kattatzu** [comment]
Hello guillenjsa, sorry for the lateness, I had forgotten about this project.

Indeed, Sbif does not provide data for holidays or holidays, the library does not really do any type of calculation or transformation of the values to cause a "Division by zero", this could come from the source, which I doubt but I don't. discard, or an error in your code for getting a zero as a response (only validation: isset($body->UFs[0]) ? $body->UFs[0]->Value: 0).

I imagine that the answer is no longer useful to you, but I answer so that it remains in history.
